### ISSUE TITLE
Response Interceptor need a retry request mechanism

### ISSUE THREAD

**Issue by davideme** [Karumi/BothamNetworking#28]
It can be usefull in order to implement
* OAuth Refresh Token
* Auto retry of Network Error

I can imagine various way to implement it, we should discuss them before a PR.

**Comment by davideme** [comment]
First we should decide, how to intercept Errors and if we should differentiate HTTPError than Others.

Second the retry mechanism, the interceptor could return a Result<HTTPResponse, RetryableError> (or a throws) and capture it and retry in HTTPClient.
OR
Provide a function in params or properties of the interceptor that retry the request.

**Comment by pedrovgs** [comment]
Just to open the discussion. What about an implementation similar to the one implemented at OkHttp?

```java
@Override
        public Response intercept(Chain chain) throws IOException {
            Request request = chain.request();

            // try the request
            Response response = chain.proceed(request);

            int tryCount = 0;
            while (!response.isSuccessful() && tryCount < 3) {

                Log.d("intercept", "Request is not successful - " + tryCount);

                tryCount++;

                // retry the request
                response = chain.proceed(request);
            }

            // otherwise just pass the original response on
            return response;
        }
```

To do this we don't need a ``BothamResponseInterceptor`` but we need to implement a ``Chain`` mechanism.

Another interesting option is to pass the ``BothamAPIClient`` instance or an protocol implemented by ``BothamAPIClient`` offering a method to send a request without execute the request interceptors. We should also change the params to receive the original request. Something like

```swift
class RetryResponseInterceptor: BothamResponseInterceptor {
   public func intercept(request: HTTPRequest, response: Result<HTTPResponse, BothamAPIClientError>, apiClient: BothamAPIClient) -> Result<HTTPResponse, BothamAPIClientError> {
      if result.error == BothamAPIClientError {
          //Retry here
          apiClient.sendRequest(httpRequest)
      } else {
          return response
      }
}
```

The problem with this implementation is that we should change ``BothanResponseInterceptor`` to use a completionHandler.

**The code shown is pseudo code, please use your imagination ;)**

**Comment by davideme** [comment]
I'm not a fan of the chain mechanism.

I prefer something like this

```Swift
    func intercept(response: HTTPResponse) -> Result<HTTPResponse, RetryableError> {
        if response.statusCode == 401 {
            /* Renew Refresh Token */
            return Result.Failure(RetryableError)
        } else {
            return Result.Success(response)
        }
    }
```
And applyResponseInterceptors is in charge of checking the result of the method and retry the request if RetryableError is returned.

**Comment by pedrovgs** [comment]
Sorry, but I don't understand how using this implementation we are going to renew the refresh token. Are the request changes needed to repeat the request going to be performed in the request interceptor? Or are we going to create a BothamAPIClient instance inside that interceptor to be able to resend the request?
